### ISSUE TITLE
gehele document

### ISSUE THREAD

**Issue by fterpstra** [Geonovum/KP-APIs-OAuthNL#1]
(via webformulier binnengekomen)
opmerking:
De   nut en noodzaak van het formuleren van een profiel op OAuth wordt in het   document niet onderbouwd. Dit geldt zowel voor iGov als voor iGov-NL. Zonder   dat gaan de ministeries van EZK en LNV niet mee in de adoptie van dit   profiel.
oplossing:

Maak   duidelijk waarom een iGov-NL profiel wenselijk is, en waarom dat leidt tot   het weglaten van bepaalde autorisatiepatronen uit de OAuth-standaard.
--

**Comment by fterpstra** [comment]
opmerking:
Ten   aanzien van de nut en noodzaak: EZK en LNV hechten waarde aan internationale   interoperabiliteit. In hoeverre is dit als criterium meegewogen bij de keuze   om een Nederlands profiel te definiëren?

oplossing:

Heroverweeg de nut en noodzaak van dit profiel   en de beoogde reikwijdte ervan. Een alternatief is bijvoorbeeld het adopteren   van de volledige OAuth-standaard, en daarop een beleid toevoegen waarin   voorkeurspatronen staan afhankelijk van type applicatie en   beveiligingsniveau.
--

**Comment by fterpstra** [comment]
OAuth is voorgedragen voor de pas toe of leguit lijst. Voorwaarde voor opname is het bestaan van een Nederlands profiel. Dit document is de versie van dit profiel. We hebben deze motivatie uitgelegd in H5 van de nederlandse API strategie. We gaan deze motivatie los bijvoegen bij het profiel zodat het beter vindbaar is. Deze eerste versie van het profiel ondersteund 1 specifieke usecase, het kan in de toekomst uitgebreid worden met meer usecases. De PTOLU houd zijn functionele reikwijdte (autorisatie voor APIs) wanneer er behoefte is aan ondersteuning van meer usecases dan nemen we die graag op in een volgende versie van het profiel.
Qua internationale interoperabiliteit: De meeste aanpassingen ten opzichte van het internationale iGov profiel zijn een verdere aanscherping die interoperabel is. We doen ook een aantal uitbreidingen. Dat geeft mogelijk internationaal interoperabiliteitsissues. We willen onze uitbreidingen indienen als changerequest voor iGov. Mochten deze niet gehonoreerd worden dan heroverwegen we de nederlandse uitbreidingen.

**Comment by rschaar-logius** [comment]
Mbt internationale interoperabiliteit: moeten we in 1.2.3 (Conformance) de tekst niet herzien, om ook conformance tussen iGov en iGov-NL expliciet te maken en niet alleen de huidige replace van iGov naar iGov-NL?
